# Couchbase Lite API
swagger: '2.0'
info:
  title: Couchbase Lite
  description: Documentation for the Couchbase Lite REST API
  version: '1.2.1'
host: localhost:5984
schemes:
  - http
tags:
  $ref: ./tags/index.yaml
consumes:
  - application/json
produces:
  - application/json
################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  $ref: ./parameters/index.yaml
paths:
  /:
    get:
      tags:
        - server
      summary: summary
      description: description
      responses:
        200:
          description: hello
  /_active_tasks:
    get:
      description: This request retrieves a list of all tasks running on the server.
      responses:
        200:
          description: 200 OK – Request completed successfully
          schema:
            $ref: '#/definitions/ActiveTasks'
  /_all_dbs:
    $ref: ./paths/_all_dbs.yaml
  /_replicate:
    post:
      description: This request starts or cancels a database replication operation.
      parameters:
        - $ref: '#/parameters/replication'
      responses:
        200:
          description: 200 OK
          schema:
            type: object
            properties:
              ok:
                type: boolean
                description: Indicates whether the replication operation was successful
              session_id:
                type: string
                description: Session identifier
  /_session:
    get:
      summary: Retrieve session information
      description: This request retrieves session information. Even though Couchbase Lite doesn’t support user logins, it implements a generic response to the _session API for compatibility with apps that might call it.
      responses:
        200:
          description: 200 OK
  /_uuids:
    get:
      summary: List of database identifiers
      description: This request retrieves a list of the database identifiers.
      responses:
        200:
          description: List of UUIDs
          schema:
            type: object
            properties:
              uuids:
                type: string
  /{db}:
    $ref: ./paths/db/db.yaml
  /{db}/_all_docs:
    $ref: ./paths/db/_all_docs.yaml
  /{db}/_bulk_docs:
    $ref: ./paths/db/_bulk_docs.yaml
  /{db}/_design/{ddoc}/_view/{view}:
    $ref: ./paths/db/_design/ddoc/_view/view.yaml
  /{db}/{doc}:
    $ref: ./paths/db/doc/doc.yaml
definitions:
  $ref: ./definitions/index.yaml