title: Couchbase Mobile
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Couchbase Mobile documentation: API references and Guides.
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll


defaults:
- scope:
    path: docs
    type: page
  values:
    layout: docs
- scope:
    path: training
    type: page
  values:
    layout: training

# Build settings
#markdown: kramdown
# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

exclude:
  - "*.screenflow"